spring.datasource.url=jdbc:postgresql://localhost:5432/ReminderBot
spring.datasource.username=Kate
spring.datasource.password=KatesPassword
telegram.bot.token=8072876524:AAEmnxk-ARnmVSoBqLuQK_YZz8ppH6fjmiE
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.enabled= true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= validate
spring.jpa.show-sql=true
